# Generated by Django 4.0.2 on 2022-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininghistory',
            name='date',
            field=models.DateField(),
        ),
    ]
