# Generated by Django 4.0.2 on 2022-02-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_traininghistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininghistory',
            name='statistics',
        ),
        migrations.AddField(
            model_name='traininghistory',
            name='statistics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='api.statistics'),
        ),
    ]
