# Generated by Django 4.0.2 on 2022-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_traininghistory_statistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininghistory',
            name='statistics',
        ),
        migrations.AddField(
            model_name='traininghistory',
            name='statistics',
            field=models.ManyToManyField(null=True, related_name='statistics', to='api.Statistics'),
        ),
    ]
