# Generated by Django 4.0.2 on 2022-02-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_traininghistory_statistics_statistics_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.traininghistory'),
        ),
    ]
